### ISSUE TITLE
Minor improvements to requirements

### ISSUE THREAD

**Issue by MaiNorapong** [jeanyjean/ku-polls#1]
> 4.&nbsp;User can specify a date range for the **polls or surveys**.
> 5.&nbsp;User can view the results of the **polls or surveys** even after the closing date.

> 7.&nbsp;User can choose whether to have an opening and closing date for the **polls or surveys**.

As Mr James has posted in the classroom this morning, use "poll" instead of "survey" for now.

The rest seems OK. The ability to vote seems to be missing though. You should include that. "editing" and "voting" is not exactly the same.

**Comment by jeanyjean** [comment]
Fixed.
